import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Story 15.1 — ADR-029: Better Auth self-hosted (replaces Supabase Auth)
 *
 * Creates the 4 tables required by Better Auth v1.x with the admin plugin.
 * IDs are text (UUID v7 generated by application domain — ADR-026 R1).
 *
 * Tables:
 * - user     : User accounts
 * - session  : Active sessions (replaces Supabase JWT)
 * - account  : OAuth provider accounts
 * - verification : Email verification / password reset tokens
 *
 * Column names are camelCase (Better Auth + Kysely convention for PostgreSQL).
 */
export class CreateBetterAuthTables1772000000000 implements MigrationInterface {
  name = 'CreateBetterAuthTables1772000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── user ──────────────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "user" (
        "id"            TEXT          NOT NULL,
        "name"          TEXT          NOT NULL,
        "email"         TEXT          NOT NULL UNIQUE,
        "emailVerified" BOOLEAN       NOT NULL DEFAULT FALSE,
        "image"         TEXT,
        "createdAt"     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        "updatedAt"     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        -- admin plugin fields
        "role"          TEXT          NOT NULL DEFAULT 'user',
        "banned"        BOOLEAN       NOT NULL DEFAULT FALSE,
        "banReason"     TEXT,
        "banExpires"    TIMESTAMPTZ,
        PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "idx_user_email" ON "user" ("email")`,
    );

    // ── session ───────────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "session" (
        "id"          TEXT          NOT NULL,
        "expiresAt"   TIMESTAMPTZ   NOT NULL,
        "token"       TEXT          NOT NULL UNIQUE,
        "createdAt"   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        "updatedAt"   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        "ipAddress"   TEXT,
        "userAgent"   TEXT,
        "userId"      TEXT          NOT NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "fk_session_user"
          FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "idx_session_userId" ON "session" ("userId")`,
    );
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "idx_session_token" ON "session" ("token")`,
    );

    // ── account ───────────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "account" (
        "id"                      TEXT          NOT NULL,
        "accountId"               TEXT          NOT NULL,
        "providerId"              TEXT          NOT NULL,
        "userId"                  TEXT          NOT NULL,
        "accessToken"             TEXT,
        "refreshToken"            TEXT,
        "idToken"                 TEXT,
        "accessTokenExpiresAt"    TIMESTAMPTZ,
        "refreshTokenExpiresAt"   TIMESTAMPTZ,
        "scope"                   TEXT,
        "password"                TEXT,
        "createdAt"               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        "updatedAt"               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        PRIMARY KEY ("id"),
        CONSTRAINT "fk_account_user"
          FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "idx_account_userId" ON "account" ("userId")`,
    );

    // ── verification ──────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "verification" (
        "id"          TEXT          NOT NULL,
        "identifier"  TEXT          NOT NULL,
        "value"       TEXT          NOT NULL,
        "expiresAt"   TIMESTAMPTZ   NOT NULL,
        "createdAt"   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        "updatedAt"   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "idx_verification_identifier" ON "verification" ("identifier")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "idx_verification_identifier"`,
    );
    await queryRunner.query(`DROP TABLE IF EXISTS "verification"`);

    await queryRunner.query(`DROP INDEX IF EXISTS "idx_account_userId"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "account"`);

    await queryRunner.query(`DROP INDEX IF EXISTS "idx_session_token"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_session_userId"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "session"`);

    await queryRunner.query(`DROP INDEX IF EXISTS "idx_user_email"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "user"`);
  }
}
